### PR TITLE
Standardize model identifier names; Support datastacks for plugins

### LINKED ISSUE #681: Revisit model naming and metadata
When the first workbench release is out, and/or the QT interface is deprecated, we should revisit the `MODEL_METADATA`/`ARGS_SPEC` questions raised in #677. 
- Do the `model_name` and `userguide_html` keys still belong in the `ARGS_SPEC`?
- Does it still make sense to have the `MODEL_METADATA` dictionary at all? Is it necessary for efficient calls to `invest list` or `/models`?
- Use consistent terminology for the different types of model names in the workbench.

### LINKED ISSUE #1700: Plugins: should be able to load in datastacks, json, logfiles
Currently this is failing because InVEST looks for an invest-like model in it's given environment space (see [models.py line 27](https://github.com/natcap/invest/blob/e6318a62e312eb6194ba574d7f97034a9844f48a/src/natcap/invest/models.py#L27)). But, the plugin is installed in the natcap namespace in it's isolated mamba env. 

I feel like this was partly redesigned specifically for plugins, but the separate environment issue seems to be a big hurdle to this being generalizable.

The specific error I see when trying is:
```
  File "C:\Users\ddenu\Workspace\Repositories\venvs\schisto\Lib\site-packages\natcap\invest\ui_server.py", line 168, in post_datastack_file
    model_id = PYNAME_TO_MODEL_ID_MAP[stack_info.model_name]
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'natcap.invest.schistosomiasis'
```

### PR DESCRIPTION
**Pull request by emlys**
## Description
Fixes #1700, fixes #681 

As I started working on #1700, I felt like the way we're using and referring to different model identifiers was becoming a problem, and so I ended up addressing that as well. Sorry it's kind of jumbled together!

## Standardize naming for model identifiers
There are three types of identifiers used for invest models:
- the python module name (e.g. `natcap.invest.annual_water_yield`)
- the user-facing model title (e.g. `Annual Water Yield`)
- the model id (e.g. `annual_water_yield`)

We've referred to all three of these with some interchangeable and overlapping names (`model_id, model_name, module_name, pyname, py_module_name, modelRunName, modelHumanName, ...`). This gets confusing, and when we document plugins for others to use, it's important to use consistent terminology. I propose standardizing on these three terms to refer to model identifiers in our code and documentation:
- `model_id` for the primary unique identifier of a model (`annual_water_yield`)
- `model_title` for the user-facing name
- `pyname` for the python module name

## Use the `model_id`, and not the `pyname`, as the primary identifier
The `pyname` has been widely used as the model identifier - in datastacks and logfiles, in server requests, and some places in the workbench. I propose that the `model_id` should replace it as the primary identifier. 

### Remove `pyname` from the workbench
The workbench in particular shouldn't need to know models' python package name, since it only interfaces with them through the server. I propose abstracting that away and using only the `model_id` on the workbench side.

### Write the `model_id` to datastacks, logfiles, and python scripts
When generating datastacks, logfiles, and python scripts, invest should include the `model_id` in an obvious and machine-readable location. When parsing datastacks, logfiles, and python scripts, invest should first look for the `model_id`. If none is found, it will look for the `pyname` to retain backwards compatibility with old datastacks.

I propose making this change when we release plugins, so that all plugin datastacks will contain the `model_id`. Thus if a `model_id` is _not_ found, we can use the `pyname`, knowing that it will be a core invest model.

## Don't filter workbench logging based on the `pyname`
The one place where the workbench relies on the `pyname` is in handling model logging. We've been using the `pyname` to apply different formatting to non-CRITICAL, non-ERROR log messages that don't come from the model module. So that the `pyname` isn't needed, I changed this to apply to all logging from `natcap.invest`, rather than `natcap.invest.{pyname}`.

## Fixing #1700 
The root cause of #1700 is that the `/post_datastack_file` endpoint reads the `pyname` from the datastack, and then uses it to look up the `model_title` and `model_id` in `natcap.invest.models`. This creates a catch-22 where the core server can't read the datastack because `natcap.invest.models` won't know about the plugin; and we can't know which plugin server to use without first reading the datastack to get the `model_id`.

By switching to the `model_id` as the primary identifier, and removing the need for the workbench to get `pyname` and `model_title` from the datastack, it's possible to read a datastack for any arbitrary model or plugin without first knowing which plugin it is.
 
## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

### CODE REVIEW

File: workbench/src/main/investUsageLogger.js [hunk 1]
```diff
@@ -13,12 +13,12 @@ const PREFIX = 'api';
 export default function investUsageLogger() {
   const sessionId = crypto.randomUUID();
 
-  function start(modelPyName, args, port) {
+  function start(modelID, args, port) {
```
Comment (emlys) [inline workbench/src/main/investUsageLogger.js:16]: This is one more functional change: for usage logging, recording model IDs rather than python package names. I'm curious what everyone thinks about the impact of this change and if it's okay to go ahead with

Comment (emlys) [reply workbench/src/main/investUsageLogger.js:16]: We'd need to update the corresponding Cloud Run function, and retain backwards compatibility for a while.

**Review by davemfish — COMMENTED** [review]
Thanks a ton for updating all this code @emlys . We will all appreciate the changes going forward. Just a few minor comments from me.

File: workbench/src/main/investLogMarkup.js [hunk 2]
```diff
@@ -2,22 +2,17 @@
...
-  for (const [cls, pattern] of Object.entries(patterns)) {
-    if (pattern.test(message)) {
-      return cls;
-    }
+export default function markupMessage(message) {
+  if (/(ERROR|CRITICAL)/.test(message)) {
+    return 'invest-log-error';
+  }
+  if (/WARNING/.test(message)) {
+    return 'invest-log-primary-warning';
```
[the remark this answers is not in the document]
Comment (emlys) [reply workbench/src/main/investLogMarkup.js:12]: Fixed in dd0068505

File: workbench/tests/renderer/logtab.test.js [hunk 3]
```diff
@@ -117,29 +117,27 @@ ValueError: Values in the LULC raster were found that are not represented under
...
-    const message = `2021-01-15 07:14:37,148 (${pyModuleName}) ... INFO`;
-    const cls = markupMessage(message, pyModuleName);
-    expect(cls).toBe('invest-log-primary');
-  });
-
-  test('Warning from the invest model gets primary-warning class attribute', () => {
-    const message = `2021-01-15 07:14:37,148 (${pyModuleName}) ... WARNING`;
-    const cls = markupMessage(message, pyModuleName);
+  test('Warning from any module gets primary-warning class attribute', () => {
+    const message = '2021-01-15 07:14:37,148 (natcap.invest.carbon) ... WARNING';
```
[the remark this answers is not in the document]
Comment (emlys) [reply workbench/tests/renderer/logtab.test.js:121]: Fixed in dd0068505

File: tests/test_datastack.py [hunk 4]
```diff
@@ -25,6 +25,17 @@
 SAMPLE_DATA_DIR = os.path.join(
     _TEST_FILE_CWD, '..', 'data', 'invest-sample-data')
 
+MOCK_MODEL_ID_TO_PYNAME = {
```
[the remark this answers is not in the document]
Comment (emlys) [reply tests/test_datastack.py:30]: Done in 5935723a4

File: tests/test_datastack.py [hunk 5]
```diff
@@ -608,7 +651,10 @@ def test_extract_parameters_from_logfile(self):
                 07/20/2017 16:37:48  natcap.invest.ui.model INFO post args.
             """))
 
-        params = datastack.extract_parameters_from_logfile(logfile_path)
+        with patch('natcap.invest.datastack.models') as p:
+            p.pyname_to_model_id = {
+                val: key for key, val in MOCK_MODEL_ID_TO_PYNAME.items()}
+            params = datastack.extract_parameters_from_logfile(logfile_path)
```
[the remark this answers is not in the document]
Comment (emlys) [reply tests/test_datastack.py]: Good catch! Done in 5935723a4

File: workbench/src/main/investUsageLogger.js (hunk 1 above)
Comment (emlys) [reply workbench/src/main/investUsageLogger.js:16]: Oh you're right, I forgot it was being translated! I think we can keep using python package names for now, and maybe change things later if we do more with usage logging.

If we do want to log plugin usage accurately, we might need to start logging the git source or something more specific - since multiple plugins, or versions of a plugin, could have the same ID and pyname. I'll make a separate issue for that.

**Review by davemfish — APPROVED** [review]
Thanks for the updates! Not sure what's up with the readthedocs build. Probably not related to this PR, right?

**Comment by emlys** [comment]
@davemfish the RTD build has been failing on the plugins feature branch for a while now - not sure what's up with it, but likely not related to these changes!

File: scripts/invest-autovalidate.py [hunk 6]
```diff
@@ -67,25 +68,25 @@ def main(sampledatadir):
         raise ValueError(f'no json files found in {sampledatadir}')
 
     for datastack_path in datastacks:
-        paramset = datastack.extract_parameter_set(datastack_path)
-        if paramset.model_name.split(".")[-1] in {
-                'delineateit', 'ndr', 'scenic_quality', 'sdr',
-                 'seasonal_water_yield', 'recreation'}:
+        if datastack_path.split(os.sep)[-2] in {'DelineateIt', 'NDR', 'ScenicQuality',
+                                            'SDR', 'Seasonal_Water_Yield', 'recreation'}:
             continue # avoid compiled modles for devoloped of plugin feature branch
```
Comment (dcdenu4) [inline scripts/invest-autovalidate.py:73]:
```suggestion
            continue # avoid compiled models for development of the plugin feature branch

```

Comment (dcdenu4) [reply scripts/invest-autovalidate.py:73]: Hopefully you don't mind allowing me to fix my poor English here...

File: src/natcap/invest/utils.py [hunk 7]
```diff
@@ -796,3 +793,50 @@ def matches_format_string(test_string, format_string):
     if re.fullmatch(pattern, test_string):
         return True
     return False
+
+
+def copy_spatial_files(spatial_filepath, target_dir):
```
Comment (dcdenu4) [inline src/natcap/invest/utils.py:798]: I didn't notice any test being moved for this function from `test_datastack` to `test_utils`, did we not have one before? Should we have one now?

**Review by dcdenu4 — CHANGES_REQUESTED** [review]
Thanks @emlys ! I only had a few things, one a selfish and shameful edit on a comment I wrote and another a question about maybe a missing test?

I saw you and @davemfish commented about usage logging, that was going to be my other question. But it seems like it should stay as is for now.

File: src/natcap/invest/utils.py (hunk 7 above)
Comment (davemfish) [reply src/natcap/invest/utils.py:798]: I don't think we have a unit test for this, which might be fine. If we want one, I suggest we add it on `main` rather than in this PR.

Comment (emlys) [reply src/natcap/invest/utils.py:798]: Correct, there wasn't a test before.

Comment (emlys) [reply src/natcap/invest/utils.py:798]: I think since we are not changing any functionality here, a test is no more necessary than it was before

Comment (dcdenu4) [reply src/natcap/invest/utils.py:798]: Sounds good to me!

File: workbench/src/renderer/app.jsx [hunk 8]
```diff
@@ -200,9 +200,8 @@ export default class App extends React.Component {
   async updateInvestList() {
     const coreModels = {};
     const investList = await getInvestModelNames();
```
Comment (dcdenu4) [inline workbench/src/renderer/app.jsx:202]: Should `getInvestModelNames` be `getInvestModelIds`?

**Review by dcdenu4 — COMMENTED** [review]
Hey @emlys, sorry, a couple last questions.

Should `modelRunName` in `renderer/components/PluginModal/index.js` be `modelRunId`?

Should 'pluginName` in `main/setupInvestHandlers` be `pluginId`?

Should `getInvestModelNames` be `getInvestModelIds` in `renderer/app.jsx`?

File: workbench/src/renderer/app.jsx (hunk 8 above)
Comment (emlys) [reply workbench/src/renderer/app.jsx]: Sure, I renamed all these

**Review by dcdenu4 — APPROVED** [review]
Thanks @emlys !!
