### PR TITLE
Workbench: validate metadata that is used to open invest models

### LINKED ISSUE #1275: Make sure two different workbench versions can run on the same system
Because of `requestSingleInstanceLock`, we don't expect multiple clients to run at the same time, but they should be able to run independently, and might not because they share some resources on the filesystem:

Workbench settings & recent jobs are stored in the browser's localstorage. If the schema for these data changes between workbench versions, something might be broken when the other version is opened.

I don't know of this happening in the wild yet, but I think it's worth testing to find out if it does. And generally adding some error-handling around corrupt data in localstorage is a good idea.

### LINKED ISSUE #1286: Workbench - handle unexpected data in localStorage
We should safeguard against loading bad data from localStorage, where we keep settings & recent runs data. It seems there are instances where bad data is written if a crash happens. For example, https://community.naturalcapitalproject.org/t/invest-3-13-0-crashing-on-start-on-macos-12-4/3684

We should add safeguards to avoid writing bad data...for example, why would an invest exception like the one from this user lead to bad data being written to the "recent runs" store?

And also safeguards when reading data from the database. It would be better to clear out the bad items, or even reset the whole database, rather than letting the error propagate to the `ErrorBoundary`.

### PR DESCRIPTION
**Pull request by davemfish**
This PR adds some validation before rendering data from the recent jobs store, to avoid rendering a card for a model that no longer exists in the current version of invest, and to skip over jobs that are somehow missing critical pieces of data.

It also adds error handling for trying to load a datastack from a deprecated model.

Fixes #1275 and fixes #1286 

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [x] Tested the affected models' UIs (if relevant)

### CODE REVIEW

File: workbench/src/renderer/server_requests.js [hunk 1]
```diff
@@ -82,7 +82,6 @@ export function fetchDatastackFromFile(payload) {
       headers: { 'Content-Type': 'application/json' },
     })
       .then((response) => response.json())
-      .catch((error) => logger.error(error.stack))
```
Comment (emlys) [inline workbench/src/renderer/server_requests.js:85]: Just making sure I understand - this error would now be caught farther up?

File: workbench/src/renderer/components/SetupTab/index.jsx [hunk 2]
```diff
@@ -274,8 +275,20 @@ class SetupTab extends React.Component {
...
-    const datastack = await fetchDatastackFromFile(filepath);
     const { pyModuleName, switchTabs, t } = this.props;
+    let datastack;
+    try {
+      datastack = await fetchDatastackFromFile(filepath);
+    } catch (error) {
+      logger.error(error);
+      alert( // eslint-disable-line no-alert
+        t(
+          'No InVEST model data can be parsed from the file:\n {{filepath}}',
```
Comment (emlys) [inline workbench/src/renderer/components/SetupTab/index.jsx:286]: I wonder if this message could provide any more information to help the user solve the problem. Maybe something like 
> File could not be opened as an InVEST model run. Are you sure this is a valid datastack for a current InVEST model?

**Review by emlys — COMMENTED** [review]
@davemfish this all makes sense! Just one suggestion about the alert message.

File: workbench/src/renderer/components/SetupTab/index.jsx (hunk 2 above)
Comment (davemfish) [reply workbench/src/renderer/components/SetupTab/index.jsx:286]: I agree it's not perfect but I'm kind of at a loss for how to improve it. This is from the "Load Parameters" button on a model's sidebar, so we're not really opening a "model run" here. If "datastack" had a clear meaning to users then I'd agree we could say, "this is not a valid datastack", but I'm afraid that term is mostly insider-jargon. 

My hope is that anyone who sees this message will just realize they clicked on the wrong file or something. If they really don't know what file they should be looking for, then that's a larger design flaw and we should try to add some guidance before the user reaches this alert. We have a tooltip that tries to do that now.

File: workbench/src/renderer/server_requests.js (hunk 1 above)
Comment (davemfish) [reply workbench/src/renderer/server_requests.js:85]: That's right. It felt better to add the user-facing alert message to UI component, so that's where the error-handling is now.

File: workbench/src/renderer/components/SetupTab/index.jsx (hunk 2 above)
Comment (emlys) [reply workbench/src/renderer/components/SetupTab/index.jsx:286]: Oh I see what you mean. Yeah, this should be fine for now.

**Review by emlys — APPROVED** [review]
