### PR TITLE
Identify plugins by `model_id@version`; display plugin version in models list

### LINKED ISSUE #1986: Bug: Loading parameters from file fails for plugins
## Description
When attempting to load parameters from a file for a plugin, the operation fails with the following error in the console: `TypeError: Cannot read properties of undefined (reading 'modelTitle') at SetupTab.loadParametersFromFile`

## To replicate
Provide detailed steps to replicate the behavior.

1. Install a plugin into workbench
2. In the Datastack Options, save parameters to json
3. (Try to) load parameters from file using the file you just created

## Expected behavior
I expect the fields to populate

## Observed behavior
No fields are populated and I get error: `TypeError: Cannot read properties of undefined (reading 'modelTitle') at SetupTab.loadParametersFromFile`

## Environment
- Operating System: MacOS Sequoia (15.5)
- InVEST version number: 3.16.0a2
- InVEST interface (Workbench, CLI, or Python API): Workbench

## Additional context
 @davemfish noted that the issue seems to stem from this block in `SetupTab.loadParametersFromFile`:
```
if (datastack.model_id === modelID) {
  this.batchUpdateArgs(datastack.args);
  switchTabs('setup');
  this.triggerScrollEvent();
} else {
  alert(
    t(
      'Datastack/Logfile for model {{modelTitle}} does not match this model.',
      { modelTitle: investList[datastack.model_id].modelTitle }
    )
  );
}

```
According to the error, `investList[datastack.model_id]` is undefined. This results in the `modelTitle` access throwing the `TypeError`.

Note that in `renderer/app.jsx`, `updateInvestList()` sets the `modelTitle` and `type` for core models, but for plugins, only the `type` is set:
```

const coreModels = {};
const investList = await getInvestModelIDs();
Object.keys(investList).forEach((modelID) => {
  coreModels[modelID] = { modelTitle: investList[modelID].model_title, type: 'core' };
});
const plugins = await ipcRenderer.invoke(ipcMainChannels.GET_SETTING, 'plugins') || {};
Object.keys(plugins).forEach((plugin) => {
  plugins[plugin].type = 'plugin';
});
this.setState({
  investList: { ...coreModels, ...plugins },
});
```

### PR DESCRIPTION
**Pull request by emlys**
## Description
Fixes #1986

Instead of hashing the `model_id@version` identifier string, just escape the periods when using `settingsStore`. For the purpose of saving and opening datastacks, each combination of `model_id` and `version` is a unique model. 

This means that datastacks are not reusable between different versions of the same plugin, which I think is fine for now, but we might want to support differently in the future.

I tested and confirmed that datastacks created from a plugin (both JSON datastacks and TGZ archives) can be opened using the "Load parameters from file" button in the sidebar.

Also adding the plugin version to the displayed title in the list of models (if it is not unique). I'm not sure if this is the right design, vs. always displaying the version.

## Checklist
- [ ] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [ ] Tested the Workbench UI (if relevant)

### CODE REVIEW

File: workbench/src/renderer/server_requests.js [hunk 1]
```diff
@@ -208,7 +208,6 @@ export async function saveToPython(payload) {
  */
 export async function archiveDatastack(payload) {
   const { port, id } = await getPortAndID(payload.model_id);
-  payload.model_id = id;
```
Comment (emlys) [inline workbench/src/renderer/server_requests.js:211]: For these two endpoints, use the original id in the format `model_id@version` rather than stripping it down to the `model_id`.

File: workbench/src/main/setupAddRemovePlugin.js [hunk 2]
```diff
@@ -164,9 +164,9 @@ export function setupAddPlugin(i18n) {
         // Uniquely identify plugin by a hash of its ID and version
         // Hashing because the version may contain dots,
```
Comment (davemfish) [inline workbench/src/main/setupAddRemovePlugin.js]: It looks like this comment could use updating

**Review by davemfish — COMMENTED** [review]
This looks good @emlys . My only minor concern is that repeating the string-escaping in so many places is a bit cumbersome and prone to us missing a spot in the future.

I wonder if it would work to replace the dots with another character (e.g. underscore) when the `pluginID` is first created and entered into the `settingsStore`, near the end of `setupAddPlugin`. Would that avoid the need to deal with dots at all the subsequent `set` and `get` calls?

File: workbench/src/main/setupAddRemovePlugin.js (hunk 2 above)
Comment (emlys) [reply workbench/src/main/setupAddRemovePlugin.js]: That's a good idea. I updated it to replace dots with underscores where the plugin ID is first set in the settings store, and then we can avoid all the escaping elsewhere.
