### PR TITLE
Restore mac code-signing via our new code-signing service

### LINKED ISSUE #1784: Renew our MacOS Code-Signing Certificate
Our mac binary builds have been failing for a few weeks now, and it appears that this is due to our Mac code-signing certificate having expired (judging by the certificate name `2025-01-16-Expiry-AppStore-App.p12`).

### PR DESCRIPTION
**Pull request by phargogh**
This PR restores mac DMG codesigning by way of our new codesigning service, which simplifies our actions YAML (since we now just build the workbench in all cases and then defer OS-specific codesigning logic to the codesigning service), and probably makes this whole process more secure by not copying certificates out of a GCS bucket and keeping the operational code on a better-protected host that we control.

NOTE: one of the puppeteer tests was reliably failing for me, co I temporarily commented out the puppeteer tests to make sure this codesigning functionality works as expected.  You can see the passing mac and windows codesigning GHA steps here:
* [Passing mac action](https://github.com/phargogh/invest/actions/runs/13505701634/job/37734678430), [signed binary](https://storage.googleapis.com/natcap-dev-build-artifacts/invest/phargogh/3.14.2.post456%2Bgc386218db/workbench/invest_3.14.2.post456%2Bgc386218db_workbench_darwin_x64.dmg) (signature info forthcoming)
* [Passing windows action](https://github.com/phargogh/invest/actions/runs/13505701634/job/37734679215), [signed binary](https://storage.googleapis.com/natcap-dev-build-artifacts/invest/phargogh/3.14.2.post456%2Bgc386218db/workbench/invest_3.14.2.post456%2Bgc386218db_workbench_win32_x64.exe) and [signature info](https://storage.googleapis.com/natcap-dev-build-artifacts/invest/phargogh/3.14.2.post456%2Bgc386218db/workbench/invest_3.14.2.post456%2Bgc386218db_workbench_win32_x64.exe.signature)

Fixes #1784

## Checklist
- [x] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
~~- [ ] Updated the user's guide (if needed)~~
~~- [ ] Tested the Workbench UI (if relevant)~~

### CODE REVIEW

File: codesigning/enqueue-current-installer.sh [hunk 1]
```diff
@@ -0,0 +1,28 @@
+#!/usr/bin/env sh
+#
+# Run this script to enqueue the windows binary for this current version of the
```
Comment (dcdenu4) [inline codesigning/enqueue-current-installer.sh:3]: Update comment to mention mac now too or leave ambiguous?

**Review by dcdenu4 — CHANGES_REQUESTED** [review]
Thanks @phargogh for migrating this over to a unified code signing process. I only had one suggestion for updating a doc string.

**Comment by dcdenu4** [comment]
Hey @phargogh, I just thought about our `makefile` which still has `codesign_mac` and `codesign_windows` endpoints. At least for Windows this is no longer tenable, should we go ahead and remove them both from the `makefile` at this point?

File: codesigning/enqueue-current-installer.sh (hunk 1 above)
Comment (phargogh) [reply codesigning/enqueue-current-installer.sh]: Updated in 3dd189d56

**Comment by phargogh** [comment]
> Hey @phargogh, I just thought about our makefile which still has codesign_mac and codesign_windows endpoints. At least for Windows this is no longer tenable, should we go ahead and remove them both from the makefile at this point?

Yeah, I was kind of waffling on this a bit.  From my perspective, the `codesign_windows` and `codesign_mac` steps are still correct processes (minus getting the certificate from GCS), so it wouldn't be _incorrect_ to have the steps in there if we ever wanted to use them again.  A case where we may want to use them again is if/when we need to manually sign an application.

Having said that, we're not actually _using_ them, and everything related to the codesigning service is contained in the codesigning directory.

Anyways, I think I've talked myself into deleting these, so they have been removed/updated in 4de580bbc

**Review by dcdenu4 — APPROVED** [review]
Thanks @phargogh for thinking about that and for the changes. This feels like the right direction to me and if we want to have a deliberate way to codesign manually in the future we can reestablish one based on the new structure here.

File: codesigning/README.md [hunk 2]
```diff
@@ -37,6 +37,17 @@ it.  This computer is assumed to run debian:bookworm at this time.  To deploy
...
 ```
 
+### Useful debugging commands
+
+* `sudo systemctl status natcap-codesign.service` will show the current status
+  of the service. Instead of `status`, you can also say `start`, `stop`, or a
+  few other verbs described in the systemctl docs.
+* `sudo journalctl -u natcap-codesign.service -n 300` will show the 300 most
+  recent log messages generated by the service.
+* `sudo journalctl -u natcap-codesign.service -n 300 --follow` will show the
```
Comment (emlys) [inline codesigning/README.md:47]: Very helpful to have this documented here!

File: codesigning/enqueue-current-installer.sh [hunk 3]
```diff
@@ -0,0 +1,28 @@
...
+# This script determines the filename of the binary that is built on the
+# current operating system and enqueues it for code signing.
+#
+# NOTE: this script must be run from the directory containing this script.
+
+version=$(python -m setuptools_scm)
+url_base=$(make -C .. --no-print-directory print-DIST_URL_BASE | awk ' { print $3 } ')
+platform=$(python -c "import platform;p=platform.system().lower();print(p if p != 'windows' else 'win32')")
+
+if [ "$platform" = "win32" ]; then
```
Comment (emlys) [inline codesigning/enqueue-current-installer.sh:12]: Would it be worth scripting this in python? Since there's already some python commands in here, and the other codesigning scripts are in python.

**Review by emlys — APPROVED** [review]
Thanks @phargogh! I am approving and I had just one suggestion about a script

File: codesigning/enqueue-current-installer.sh (hunk 3 above)
Comment (phargogh) [reply codesigning/enqueue-current-installer.sh]: Yes!  Absolutely, both because several components of this are python anyways and also because python will allow us to run this script from any CWD, as long as we know the location of the script (which python should always know).  Patched in 99e294921

**Comment by phargogh** [comment]
Thanks @emlys !  I just replaced the bash script with a python script (which is now working as expected in this branch on my fork) and I think we are ready to go.
