### PR TITLE
Bugfixes for extracting datastack archive

### LINKED ISSUE #1993: Cannot open a TGZ datastack archive
## Description
Opening a TGZ datastack archive no longer works.

## To replicate
Provide detailed steps to replicate the behavior.

1. Open a model, load inputs and save as a datastack archive ("Parameters and data")
2. Go to "Browse to a datastack or InVEST logfile" and select the archive you created
3. Observe that the "No InVEST model data can be parsed from the file" alert is displayed. There is no prompt to choose an extraction location. The server logging indicates that the extraction path is missing.

```
[1] [11:50:55.833] [undefined] 06/02/2025 11:50:55  natcap.invest.ui_server ERROR    Exception on /api/post_datastack_file [POST]
[1] Traceback (most recent call last):
[1]   File "/Users/emily/invest/bash/envs/main/lib/python3.13/site-packages/flask/app.py", line 1511, in wsgi_app
[1]     response = self.full_dispatch_request()
[1]   File "/Users/emily/invest/bash/envs/main/lib/python3.13/site-packages/flask/app.py", line 919, in full_dispatch_request
[1]     rv = self.handle_user_exception(e)
[1]   File "/Users/emily/invest/bash/envs/main/lib/python3.13/site-packages/flask_cors/extension.py", line 176, in wrapped_function
[1]     return cors_after_request(app.make_response(f(*args, **kwargs)))
[1]                                                 ~^^^^^^^^^^^^^^^^^
[1]   File "/Users/emily/invest/bash/envs/main/lib/python3.13/site-packages/flask/app.py", line 917, in full_dispatch_request
[1]     rv = self.dispatch_request()
[1]   File "/Users/emily/invest/bash/envs/main/lib/python3.13/site-packages/flask/app.py", line 902, in dispatch_request
[1]     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
[1]            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^
[1]   File "/Users/emily/invest/src/natcap/invest/ui_server.py", line 167, in post_datastack_file
[1]     stack_type, stack_info = datastack.get_datastack_info(
[1]                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
[1]         payload['filepath'], payload.get('extractPath', None))
[1]         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1]   File "/Users/emily/invest/src/natcap/invest/datastack.py", line 150, in get_datastack_info
[1]     raise ValueError('extract_path must be provided if using archive')
[1] ValueError: extract_path must be provided if using archive
```

### LINKED ISSUE #1996: Workbench load datastack (tgz) can easily overwrite user's data
## Description
Loading a `tgz` datastack includes a step to extract the data from the archive. Users first browse to the `tgz`, then browse again to choose a folder to extract data to. The problem is, this `extract_path` will be removed and re-created if it already exists. User's are unaware of this, so if they choose an existing folder rather than creating a new one, they risk losing data.  We should probably always create a new directory within the location selected by the user to avoid this.

## To replicate
This replicates from the model tab's "Load Parameters" button. It would also replicate from the Home tab's "Browse" button, except there's another bug there first (#1993).

### PR DESCRIPTION
**Pull request by davemfish**
Fixes #1996 
Fixes #1993 

Loading parameters from an archive via the Workbench will,
1. prompt the user to first choose a datastack to load from, then if an archive was chosen,
2. prompt the user to select a location to extract the data, and
3. create a new folder in that location named from the basename of the datastack file.

* Code for the Home page "browse" button and the model tab's "Load" button has been unified in a `utils.js` function.
* Some tests were updated because these changes seemed to illuminate a race condition in the tests. And some warnings about missing props during tests were resolved.
* In filesystem dialog boxes, button labels are used instead of dialog box headers whenever the default "Open" label is not descriptive enough. Because dialog headers don't seem to exist on MacOS.

## Checklist
- [x] Updated HISTORY.rst and link to any relevant issue (if these changes are user-facing)
- [ ] Updated the user's guide (if needed)
- [x] Tested the Workbench UI (if relevant)

### CODE REVIEW

File: workbench/src/renderer/utils.js [hunk 1]
```diff
@@ -38,3 +42,41 @@ export function openLinkInBrowser(event) {
...
+  const { t } = i18n;
+  let datastack;
+  try {
+    if (filepath.endsWith('gz')) { // .tar.gz, .tgz
+      const extractLocation = await ipcRenderer.invoke(
+        ipcMainChannels.SHOW_OPEN_DIALOG,
+        {
+          title: i18n.t('Choose a directory'),
+          buttonLabel: t('Extract archive here'),
+          properties: ['openDirectory, createDirectory'],
```
Comment (dcdenu4) [inline workbench/src/renderer/utils.js]:
```suggestion
          properties: ['openDirectory', 'createDirectory'],
```

**Review by dcdenu4 — APPROVED** [review]
